### PR TITLE
PLAT-7889 Sets eniconfig whilst installing vpc-cni addon

### PR DESCRIPTION
**Pull request by miguelhar**
[PLAT-7889](https://dominodatalab.atlassian.net/browse/PLAT-7889)
- Moves eni configs creation to vpc-cni install.
- Removes out of band creation of eniconfigs

### CODE REVIEW

**Review by ddl-dclegg — COMMENTED** [review]
Looks good to me, was this tested in a deployment somewhere?

**Comment by ddl-dclegg** [comment]
@miguelhar Since it's holding this back, and since we don't actually _name_ an AMI "dev-v2" (it's a prefix), should we update the filter here to a wildcard? 
image
image

**Review by ddl-dclegg — APPROVED** [review]

**Comment by miguelhar** [comment]
> Looks good to me, was this tested in a deployment somewhere?

Ci tests a deploy and an upgrade from the latest released module.

**Comment by miguelhar** [comment]
> Details

https://app.circleci.com/pipelines/github/dominodatalab/terraform-aws-eks/5902/workflows/63edbd9b-4972-442a-9cc1-8322db5d90c7/jobs/4106/parallel-runs/0/steps/0-119?invite=true#step-119-2388_94

**Review by fraenkel — APPROVED** [review]

**Comment by ddl-dclegg** [comment]
> Ci tests a deploy and an upgrade from the latest released module.

Granted, but I was asking about testing prior to CI. The template error might've been caught prior to CI if it was, so while it _looked_ ready it may not have been at the time. Anyway... 👍

**Pull request merged**
